backend:
  name: git-gateway
  branch: main



media_folder: public/assets/images
public_folder: /assets/images

collections:
  - name: "activities"
    label: "Community Activities"
    folder: "src/content/activities"
    create: true
    slug: "{{year}}-{{slug}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Activity", name: "description", widget: "text" }
